### ISSUE TITLE
Query beans are missing

### ISSUE THREAD

**Issue by AlekseyMko** [ebean-orm-examples/example-java8#2]
Hello!

I cheched out the project but looks like query package with Query beans are missing.
I found then only in example-kotlin.

Is there some reason for this?

Thanks

**Comment by rbygrave** [comment]
They are generated via the java annotation processor ... so they appear in
target/generated-sources as part of compile (IDE compile or maven compile).

So they are not in src/main, is that what you mean?


Cheers, Rob.

**Comment by AlekseyMko** [comment]
Sorry.

"So they are not in src/main, is that what you mean?"
yes

I am new to Ebean.
So now I know that this files are generated during compile process.
I just was confused when found them in example-kotlin.

Thanks

**Comment by rbygrave** [comment]
No problem.  We do generate the 'kotlin query beans' ... Via maven plugin at the moment (can't generate them with kotlin kapt currently).

So yes, we do it a couple of different ways.
